name: "mysql-test"
parameter:
- key: GetPhase
  value: "kubectl get #{kind} #{name} -o=jsonpath='{.status.phase}'"
- key: GetRevision
  value: "kubectl get #{kind} #{name} -o=jsonpath='{.metadata.resourceVersion}'"
- key: DeleteAllSlave
  value: "slaveLists=$(kubectl  get mysqlcluster  #{name}  -o jsonpath=\"{.status.conditions[?(@.type=='Slave')].name}\");for element in ${slaveLists[@]}; do kubectl delete pod $element ;done;"
- key: DeleteOneMaster
  value: "masterLists=$(kubectl  get mysqlcluster  #{name}  -o jsonpath=\"{.status.conditions[?(@.type=='Master')].name}\")&& masterLists=($masterLists) && kubectl delete pod  ${masterLists[0]}"
- key: kind
  value: mysqlcluster
- key: name
  value: mysql
jobs:
  # 初始化状态检查
  - name: "Init"
    timeout: 2m
    interval: 5s
    verificate:
      - cmd: #{GetPhase}
        value: "Running"
        name: "phaseRunning"
  # 删除所有slave测试
  - name: "DeleteAllSlave"
    cmd: #{DeleteAllSlave}
    timeout: 2m
    initTime: 5s
    interval: 5s
    variable:
      - key: resourceVersion
        valueFromCmd: #{GetRevision}
    verificate:
      - cmd: #{GetRevision}
        operator: "noEqual"
        name: "versionChange"
        value: "@resourceVersion"
      - cmd: #{GetPhase}
        value: "Running"
        name: "phaseRunning"
  # 删除一个master测试
  - name: "DeleteOneMaster"
    cmd: #{DeleteOneMaster}
    timeout: 2m
    initTime: 5s
    interval: 5s
    variable:
      - key: resourceVersion
        valueFromCmd: #{GetRevision}
    verificate:
      - cmd: #{GetRevision}
        operator: "noEqual"
        name: "versionChange"
        value: "@resourceVersion"
      - cmd: #{GetPhase}
        value: "Running"
        name: "phaseRunning"





